### ISSUE TITLE
Different colors in the navigation icons

### ISSUE THREAD

**Issue by leonardo-sj** [RobinCK/vue-gallery#9]
1) I have just installed the vue-gallery and using the same [code that is published as a sample](https://fiddle.jshell.net/Robin_ck/LffrLb2k) in Fiddle, I have obtained different colors in the navigation icons (image below - The image on the left side of the red bar is the one displayed on Fiddle and the right one is in my local machine).
The close icon is almost as dark as background and it can confuse some users.
What would be the reason of this difference since the code is the same ?

2) Is there a way to close the gallery when user clicks outside the image ?

![icons](https://user-images.githubusercontent.com/2694753/33080614-b6b7bc4e-cebf-11e7-8553-1695896a422b.png)

**Comment by leonardo-sj** [comment]
The problem described in first issue (the different colours) is caused by the use of bootstrap CSS (link below).
Does someone know how to workaround it using both (vue-gallery and  bootstrap CSS) ?

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

**Comment by RobinCK** [comment]
Hello @leonardo-sj 
```
.blueimp-gallery a.prev {border-color: red; color: red !important;}
.blueimp-gallery a.next {border-color: blue; color: blue !important;}
```

[Example fiddle](https://fiddle.jshell.net/LffrLb2k/18/)

**Comment by leonardo-sj** [comment]
Thank you @RobinCK . It worked.
In Vue component, it worked only if it is not scoped.
Is there a way to make it scoped ?

Source sample:
```html
<template>
    <div>
        <gallery :images="images" :index="index" @close="index = null"></gallery>
        <div class="gallery" >
            <template  v-for="(item, itemIndex) in items">
            <!-- show thumbs grid -->
            </template>
        </div>
    </div>
</template>
```
```css
<style>
.blueimp-gallery a.prev {
  border-color: #fff;
  color: #fff !important;
}
.blueimp-gallery a.next {
  border-color: #fff;
  color: #fff !important;
}
.blueimp-gallery a.close {
  border-color: #fff;
  color: #fff !important;
}
</style>
<style scoped>
h1,
h2,
h3,
footer,
.gallery {
  text-align: center;
}
/* others ... */
</style>
```
